# Use root/example as user/password credentials
version: '3.1'

services:
  bazarik-db:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: bazarik
      MARIADB_ROOT_HOST: '%'
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: mariadb
    volumes:
      - data:/var/lib/mysql
      - logs:/var/log/mysql
    ports:
      - "3306:3306"
    networks:
      - bazarik
  
  bazarik-be-1:
    image: bazarik-be
    ports:
      - "8080:8080"
    networks:
      - bazarik

  bazarik-be-2:
    image: bazarik-be
    ports:
      - "8085:8080"
    networks:
      - bazarik

  bazarik-fe:
    image: bazarik-fe
    ports:
      - "4200:80"
    networks:
      - bazarik

  # bazarik-fe-2:
  #   image: bazarik-fe
  #   ports:
  #     - "4201:80"
  #   networks:
  #     - bazarik

networks:
  bazarik:
    name: bazarik
    driver: bridge
    external: true

volumes:
  data:
  logs:
