# Use root/example as user/password credentials
version: '3.1'

services:
  bazarik-db:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: bazarik
      MARIADB_ROOT_HOST: '%'
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: mariadb
    volumes:
      - data:/var/lib/mysql
      - logs:/var/log/mysql
    ports:
      - "3306:3306"
  
  bazarik-be:
    image: bazarik-be
    ports:
      - "8080:8080"

  bazarik-fe:
    image: bazarik-fe
    ports:
      - "4200:80"

networks:
  bazarik:
    name: bazarik
    driver: bridge
    external: true

volumes:
  data:
  logs:
