# Use root/example as user/password credentials
version: '3.1'

services:
  bazarik:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: bazarik
      MARIADB_ROOT_HOST: '%'
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: mariadb
    volumes:
      - data:/var/lib/mariadb
      - logs:/var/log/mariadb
    ports:
      - "3306:3306"

volumes:
  data:
  logs:
