# Use root/example as user/password credentials
version: '3.1'

services:
  bazarik-db:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: bazarik
      MARIADB_ROOT_HOST: '%'
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: mariadb
    volumes:
      - data:/var/lib/mysql
      - logs:/var/log/mysql
    ports:
      - "3306:3306"
    networks:
      - bazarik #je nutné mať aj databázu v tom istom networku, ako sú be-1 a be-2, aby spolu mohli komunikovať

  # bazarik-rabbitmq-server:
  #   image: rabbitmq:management
  #   ports:
  #     - "8082:8080"
  #   networks:
  #     - bazarik

  # bazarik-rabbitmq:
  #   image: bazarik-rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   networks:
  #     - bazarik

  bazarik-be-1:
    image: bazarik-be
    ports:
      - "8080:8080"
    environment:
      - DB_URL=bazarik-db
    networks:
      - bazarik

  bazarik-be-2:
    image: bazarik-be
    ports:
      - "8081:8080"
    environment:
      - DB_URL=bazarik-db
    networks:
      - bazarik

  bazarik-fe:
    image: bazarik-fe
    ports:
      - "80:80"
    networks:
      - bazarik

networks:
  bazarik:
    name: bazarik
    driver: bridge
    external: true

volumes:
  data:
  logs:
